# Numpy Go

## Compare a[:][:] and a[:, :]

In [ ]:
import numpy as np

I = np.eye(10)

# compare difference
print(I[0:4][0:3])
print(I[0:4, 0:3])

## Compare np.vstack(), np.hstack(), np.concatenate()

In [22]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

print('vstack:\n', np.vstack((a, b))) # Stack arrays in sequence vertically (row wise). @1
print('hstack:\n', np.hstack((a, b))) # Stack arrays in sequence horizontally (column wise). @2
print('concatenate:\n', np.concatenate((a, b))) # Join a sequence of arrays along an existing axis. @3

vstack:
 [[1 2 3]
 [2 3 4]]
hstack:
 [1 2 3 2 3 4]
concatenate:
 [1 2 3 2 3 4]


In [24]:
c = np.array([[1], [2], [3]])
d = np.array([[2], [3], [4]])

print('vstack:\n', np.vstack((c, d))) # Stack arrays in sequence vertically (row wise). @1
print('hstack:\n', np.hstack((c, d))) # Stack arrays in sequence horizontally (column wise). @2
print('concatenate:\n', np.concatenate((c, d))) # Join a sequence of arrays along an existing axis. @3

vstack:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
hstack:
 [[1 2]
 [2 3]
 [3 4]]
concatenate:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


@1: This is equivalent to concatenation along the **first axis** after 1-D arrays of shape `(N,)` have been reshaped to `(1,N)`.

@2: This is equivalent to concatenation along the **second axis**, except for 1-D arrays where it concatenates along the first axis.

@3: `concatenate((a1, a2, ...), axis=0, out=None)`. **Any axis** can be choosen. Default axis is 0.

**Summary in Chinese:**

`np.concatenate` 默认是把矩阵的第 0 轴（第 1 个轴，批量轴）连接起来的. 特例：向量没有批量轴，此时直接首尾串联. 也可以选择 `axis`.

`np.vstack` 是通过 0 轴（第 1 个轴，批量轴）把矩阵连接起来的，特例：遇见向量时，通过为向量添加新轴（批量轴），然后再进行连接.

`np.hstack` 是通过第 2 个轴把矩阵连接起来的. 特例：向量没有 "第 2 个轴"，直接首位相接.

在面对有批量轴的矩阵时: `np.concatenate` 的默认行为和 `np.vstack` 是相同的. 其之间的不同仅在于面对向量时.

在面对向量时: `np.concatenate` 的默认行为和 `np.hstack` 是相同的. 

## Generating Arrays

In [35]:
import numpy as np

A = np.array([[n+10*m for n in range(5)] for m in range(5)])
print('A:\n', A)

B = np.random.randint(100, size=(5, 5)) # @1
print('B:\n', B)

C = np.arange(25).reshape(5, 5)
print('C:\n', C)

A:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
B:
 [[23  2 55 85  7]
 [95 79 19 45 94]
 [13  3 94 62  7]
 [57 13 35 77 24]
 [88  3 50 35 21]]
C:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


@1: `randint(low, high=None, size=None, dtype='l')` Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval \[`low`, `high`). If `high` is `None` (the default), then results are from [0, `low`).

## Compare flatten(), ravel()

In [37]:
import numpy as np

A = np.array([[n+10*m for n in range(5)] for m in range(5)])

B = A.flatten() # Return a copy of the array collapsed into one dimension.
print('B:\n', B)

C = A.ravel() # Same effect with flatten(). But as we change C, A also changes
print('C:\n', C)

B[0] = 99
print('A after change B:\n', A)

C[0] = 99
print('A after change C:\n', A)

B:
 [ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]
C:
 [ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]
A after change B:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
A after change C:
 [[99  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


So we need to avoid use `np.ravel()` as much as possible

## Slicing

In [30]:
import numpy as np

A = np.array([[n+10*m for n in range(5)] for m in range(5)])

# compare these two:
print(A[[1,2,3], [1,2,3]])
print(A[[1,2,3], 1:4])



[11 22 33]

[[11 12 13]
 [21 22 23]
 [31 32 33]]
